# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.0.5 on 2026-10-03 15:34

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_cloudflare', '0007_waf_rule_zones_state'),
        ('netbox_dns', '0031_record_netbox_dns_record_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareZoneSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('bot_fight_mode', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflare_settings', to='netbox_dns.zone')),
            ],
            options={
                'verbose_name': 'Cloudflare Zone Settings',
                'verbose_name_plural': 'Cloudflare Zone Settings',
                'ordering': ['zone'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
